force-app/main/default/objects/Formulary__c/Formulary__c.object-meta.xml
<CustomObject>
    <label>Formulary</label>
    <nameField>
        <displayFormat>MRF-{0000}</displayFormat>
        <label>Formulary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formulary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulary__c/fields/Backorder__c.field-meta.xml
<CustomField>
    <fullName>Backorder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Backorder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Formulary__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Formulary</relationshipLabel>
    <relationshipName>Formulary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Formulary__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Compounded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/MyDataFactory.cls
@isTest
public class MyDataFactory {
    public static void insertTestPatient() {
        Patient__c pt = new Patient__c();
        pt.Name = 'Test Patient';
        pt.First_Name__c = 'Test First Name';
        pt.Date_Of_Birth__c = Date.today();
        insert pt;
    }

    public static void insertTestFormulary() {
        Formulary__c f = new Formulary__c();
        f.Name = 'Test Formulary';
        f.Inventory__c = 100;
        f.Type__c = 'Commercial';
        f.Backorder__c = false;
        insert f;
    }

    public static void insertTestPrescription() {
    }
}