force-app/main/default/objects/Formulary__c/Formulary__c.object-meta.xml
<CustomObject>
    <label>Formulary</label>
    <nameField>
        <displayFormat>MRF-{0000}</displayFormat>
        <label>Formulary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formulary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulary__c/fields/Backorder__c.field-meta.xml
<CustomField>
    <fullName>Backorder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Backorder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Formulary__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Formulary</relationshipLabel>
    <relationshipName>Formulary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Formulary__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Compounded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Daily_Dose__c.field-meta.xml
<CustomField>
    <fullName>Daily_Dose__c</fullName>
    <inlineHelpText>Please enter daily dose in #. 
e.g.) 2 T BID = 6, 1 puff BID = 2. Leave blank if not applicable.</inlineHelpText>
    <label>Daily Dose</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Formulary__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FormularyTriggerTest.cls
@isTest
public class FormularyTriggerTest {
    @isTest static void FormularyTriggerTest(){

        Formulary__c f = new Formulary__c();
        f.Name = 'Test Formulary';
        f.Inventory__c = 100;
        f.Type__c = 'Commercial';
        f.Backorder__c = false;
        insert f;

        Patient__c pt = new Patient__c();
        pt.Name = 'Test Patient';
        pt.First_Name__c = 'Test First Name';
        pt.Date_Of_Birth__c = Date.today();
        insert pt;

        Prescription__c rx = new Prescription__c();
        rx.Patient__c = pt.Id;
        rx.Product__c = f.Id;
        rx.Quantity__c = 30;
        rx.Daily_Dose__c = 1;
        insert rx;

        
        f.Backorder__c = true;
        test.startTest();
        System.debug(f);
        update f;
        test.stopTest();

        // Assert
        // System.assertEquals(false, f.backorder__c);
    }
    

    // @isTest(seeAllData=true)
    // public static void FormularyTriggerTest() {
    //     Formulary__c f = [SELECT Id FROM Formulary__c LIMIT 1];
    //     f.Backorder__c = TRUE;
    //     Prescription__c[] p = [SELECT Prescription__c FROM ]
    //     update f;
    // }
}