force-app/main/default/objects/Formulary__c/Formulary__c.object-meta.xml
<CustomObject>
    <label>Formulary</label>
    <nameField>
        <displayFormat>MRF-{0000}</displayFormat>
        <label>Formulary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formulary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Formulary__c/fields/Backorder__c.field-meta.xml
<CustomField>
    <fullName>Backorder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Backorder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <displayFormat>Rx-{000000}</displayFormat>
        <label>Prescription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Formulary__c</referenceTo>
    <relationshipLabel>Prescriptions</relationshipLabel>
    <relationshipName>Prescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormularyTriggerHandler.cls
public class FormularyTriggerHandler {

    public static void handleBackorderedFormulary(List<Formulary__c> oldList) {
        for(Formulary__c form : oldList) {
            if(form.Backorder__c == true) {

                Patient__c[] patientList = [SELECT Id FROM Patient__c WHERE Id IN (
                    SELECT Patient__c FROM Prescription__c WHERE Product__c = :form.id
                    )];
                
                for(Patient__c patient : patientList) {
                    Task newTask = new Task();
                    newTask.OwnerId = UserInfo.getUserId();
                    newTask.Subject = 'Notify patient about the backorder on prescription';
                    newTask.Status = 'In Progress';
                    newTask.WhatId = patient.Id;
                }
            }
        }
    }
}